name: scaling-v2
channels:
  - conda-forge
dependencies:
  - python=3.9

  # FFCV related things
  - pkg-config
  - compilers
  - libjpeg-turbo
  - opencv

  # Supercloud compatibility
  - libacl

  # For Nvidia RAPIDS
  - cudatoolkit=11.5
